part of 'server_repository.dart';

/// Becoming a member, and everything about being one.
///
/// The first three run *before* the caller is a member — or before they have a
/// key at all — which is the whole reason they are edge functions rather than
/// table calls: there is no row yet for a policy to check them against.
/// Everything after is ordinary PostgREST under migration 002.
mixin _AuthApiMixin {
  ServerDb get _db;

  Future<APIResponse> _post(
    String supabaseUrl,
    String functionName,
    Map<String, dynamic> body, {
    String? bearerToken,
  });

  /// Sign in with a SIWS message + signature. Proxied to GoTrue's web3 grant
  /// server-side (so no anon key is needed client-side). Returns the GoTrue
  /// session (access_token + refresh_token).
  Future<APIResponse> login(
    String supabaseUrl, {
    required String message,
    required String signature,
  }) {
    return _post(supabaseUrl, 'login', {
      'message': message,
      'signature': signature,
    });
  }

  /// Resolve an invite code to its server (id + name) without consuming it.
  /// Needed before login/register so the per-(host, serverId) SIWS identity can
  /// be derived when several servers share one Supabase project.
  Future<({bool success, String? serverId, String? serverName, String? error})>
  resolveInvite(String supabaseUrl, String inviteCode) async {
    final response = await _post(supabaseUrl, 'resolve_invite', {
      'invite_code': inviteCode,
    });
    if (!response.success || response.data is! Map) {
      return (
        success: false,
        serverId: null,
        serverName: null,
        error: response.error,
      );
    }
    final data = response.data as Map<String, dynamic>;
    return (
      success: true,
      serverId: data['server_id'] as String?,
      serverName: data['server_name'] as String?,
      error: null,
    );
  }

  /// Register a server profile bound to the caller's SIWS identity.
  /// [bearerToken] is the GoTrue access token obtained from [login]. Returns
  /// full server context (no token — the client already holds the JWT).
  Future<APIResponse> register(
    String supabaseUrl, {
    required String bearerToken,
    required String inviteCode,
    required String publicKey,
    required String stableId,
    required String username,
    required String displayName,
  }) {
    return _post(supabaseUrl, 'register', {
      'invite_code': inviteCode,
      'public_key': publicKey,
      'stable_id': stableId,
      'username': username,
      'display_name': displayName,
    }, bearerToken: bearerToken);
  }

  /// Check whether a username is available on the given server.
  Future<APIResponse> isUsernameAvailable(String supabaseUrl, String username) {
    return _post(supabaseUrl, 'is_username_available', {'username': username});
  }

  /// Create a plain invite code. Invites carry no permissions — members join
  /// with the baseline role and are given more from the roles editor
  /// afterwards.
  /// [maxUses] null = unlimited, 1 = single-use (default).
  /// [expiresInSeconds] null = never expires.
  /// The code is generated by the column default, and the policy refuses any
  /// permission the caller doesn't hold themselves.
  Future<APIResponse> createInvite(
    String supabaseUrl, {
    required String anonKey,
    required String serverId,
    required String userId,
    String? bearerToken,
    int? maxUses = 1,
    int? expiresInSeconds,
    bool isBot = false,
    String? roleId,
  }) {
    return ServerDb.run(() async {
      final db = _db.client(supabaseUrl, anonKey, bearerToken);
      final row = await db
          .from('invites')
          .insert({
            'server_id': serverId,
            'created_by': userId,
            'max_uses': maxUses,
            // Decided when the link is minted and never afterwards — there is
            // no UPDATE grant on invites, so one link cannot quietly become the
            // other kind (migration 014).
            'is_bot': isBot,
            // The role this link hands out, or nothing for a plain one. The
            // policy refuses a role the minter does not outrank, so a link can
            // still never carry more than its maker holds (migration 025).
            'role_id': ?roleId,
            if (expiresInSeconds != null)
              'expires_at': DateTime.now()
                  .toUtc()
                  .add(Duration(seconds: expiresInSeconds))
                  .toIso8601String(),
          })
          .select('code')
          .single();
      return {'invite_code': row['code']};
    });
  }

  /// Update the caller's own display name and/or avatar path.
  /// [clearAvatar] sends an explicit null, which removes the picture.
  ///
  /// There is no target parameter and there cannot be one: the column grant
  /// covers only these fields, and the policy only ever matches your own row.
  Future<APIResponse> updateProfile(
    String supabaseUrl, {
    required String anonKey,
    required String userId,
    String? bearerToken,
    String? displayName,
    String? avatarPath,
    bool clearAvatar = false,
  }) {
    return ServerDb.run(() async {
      final db = _db.client(supabaseUrl, anonKey, bearerToken);
      final row = await db
          .from('users')
          .update({
            'display_name': ?displayName,
            if (clearAvatar)
              'avatar_path': null
            else
              'avatar_path': ?avatarPath,
          })
          .eq('id', userId)
          .select('id, username, display_name, avatar_path')
          .single();
      return row;
    });
  }

  /// Every member of the server, with permissions and moderation state.
  /// Members can see each other; changing any of it goes through the RPCs.
  Future<APIResponse> listUsers(
    String supabaseUrl, {
    required String anonKey,
    String? bearerToken,
  }) {
    return ServerDb.run(() async {
      final db = _db.client(supabaseUrl, anonKey, bearerToken);
      final rows = await db
          .from('users')
          .select(
            'id, username, display_name, avatar_path, chat_public_key, '
            'is_muted, is_deafened, is_banned, is_bot, manifest, '
            'is_server_admin, is_channel_manager, can_create_tokens',
          )
          .order('username');
      return {
        'users': [
          for (final u in (rows as List).cast<Map<String, dynamic>>())
            ServerUserRow.of(u),
        ],
      };
    });
  }
}
