// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `enum_windows_proc`, `spawn_audio_capture_thread`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `start_audio_capture`

/// List all visible windows that can be used as audio sources on Windows.
Future<List<AudioSourceWindows>> listAudioSourcesWindows() => RustLib
    .instance
    .api
    .crateApiScreenshareAudioWindowsListAudioSourcesWindows();

/// Represents an audio source (visible window) that can be captured on Windows.
class AudioSourceWindows {
  final String title;
  final int pid;

  const AudioSourceWindows({required this.title, required this.pid});

  @override
  int get hashCode => title.hashCode ^ pid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioSourceWindows &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          pid == other.pid;
}
