// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_monitor_source_name`, `spawn_audio_capture_thread`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioCaptureCommand`, `AudioCaptureHandle`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `start_audio_capture`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `terminate`

/// List all active PulseAudio sink-inputs (audio sources).
Future<List<AudioSource>> listAudioSources() =>
    RustLib.instance.api.crateApiScreenshareAudioLinuxListAudioSources();

/// Represents an audio source that can be captured
class AudioSource {
  final int index;
  final int sink;
  final String appName;
  final String binary;
  final String mediaName;

  const AudioSource({
    required this.index,
    required this.sink,
    required this.appName,
    required this.binary,
    required this.mediaName,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      sink.hashCode ^
      appName.hashCode ^
      binary.hashCode ^
      mediaName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioSource &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          sink == other.sink &&
          appName == other.appName &&
          binary == other.binary &&
          mediaName == other.mediaName;
}
