// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `encode_thumbnail`, `new`, `run_capture_loop`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SendableFrame`, `WindowsTimerResolutionGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `spawn_capture_thread`

Future<Uint8List?> getCaptureSourceThumbnail({
  required bool captureFullScreen,
  required int sourceIndex,
}) => RustLib.instance.api.crateApiScreenshareCaptureGetCaptureSourceThumbnail(
  captureFullScreen: captureFullScreen,
  sourceIndex: sourceIndex,
);

/// List available capture sources for the requested source type.
Future<List<CaptureSource>> listCaptureSources({
  required bool captureFullScreen,
}) => RustLib.instance.api.crateApiScreenshareCaptureListCaptureSources(
  captureFullScreen: captureFullScreen,
);
