// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `run_capture_loop`

/// Spawn the video capture thread.
/// Returns a command sender and the thread handle.
Future<(SenderCaptureCommand, JoinHandle)> spawnCaptureThread({
  required bool captureCursor,
  required DesktopCaptureSourceType sourceType,
  required int fps,
  required int resolution,
  required ArcMutexOptionVideoResolutionCondvar resolutionSignal,
  required ArcMutexOptionNativeVideoSource videoSourceSlot,
}) => RustLib.instance.api.crateApiScreenshareCaptureSpawnCaptureThread(
  captureCursor: captureCursor,
  sourceType: sourceType,
  fps: fps,
  resolution: resolution,
  resolutionSignal: resolutionSignal,
  videoSourceSlot: videoSourceSlot,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < Option < NativeVideoSource > > >>>
abstract class ArcMutexOptionNativeVideoSource implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < (Mutex < Option < VideoResolution > > , Condvar) >>>
abstract class ArcMutexOptionVideoResolutionCondvar
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DesktopCaptureSourceType>>
abstract class DesktopCaptureSourceType implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< JoinHandle < () >>>
abstract class JoinHandle implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Sender < CaptureCommand >>>
abstract class SenderCaptureCommand implements RustOpaqueInterface {}
