// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

/// Publish a screen-share video track to the given room.
Future<void> publishVideoTrack({
  required Room room,
  required NativeVideoSource bufferSource,
  required ScreenShareConfig config,
}) => RustLib.instance.api.crateApiScreenshareTrackPublishVideoTrack(
  room: room,
  bufferSource: bufferSource,
  config: config,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NativeVideoSource>>
abstract class NativeVideoSource implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Room>>
abstract class Room implements RustOpaqueInterface {}
