// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CaptureCommand`, `ScreenShareSession`

class ScreenShareConfig {
  final String livekitUrl;
  final String livekitToken;
  final String channelId;
  final String identity;
  final String displayName;
  final int resolution;
  final int fps;
  final int bitrate;
  final bool shareAudio;
  final bool captureFullScreen;

  /// Video codec to use: "H264", "VP8", "VP9", or "AV1"
  final String codec;

  const ScreenShareConfig({
    required this.livekitUrl,
    required this.livekitToken,
    required this.channelId,
    required this.identity,
    required this.displayName,
    required this.resolution,
    required this.fps,
    required this.bitrate,
    required this.shareAudio,
    required this.captureFullScreen,
    required this.codec,
  });

  @override
  int get hashCode =>
      livekitUrl.hashCode ^
      livekitToken.hashCode ^
      channelId.hashCode ^
      identity.hashCode ^
      displayName.hashCode ^
      resolution.hashCode ^
      fps.hashCode ^
      bitrate.hashCode ^
      shareAudio.hashCode ^
      captureFullScreen.hashCode ^
      codec.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScreenShareConfig &&
          runtimeType == other.runtimeType &&
          livekitUrl == other.livekitUrl &&
          livekitToken == other.livekitToken &&
          channelId == other.channelId &&
          identity == other.identity &&
          displayName == other.displayName &&
          resolution == other.resolution &&
          fps == other.fps &&
          bitrate == other.bitrate &&
          shareAudio == other.shareAudio &&
          captureFullScreen == other.captureFullScreen &&
          codec == other.codec;
}
