// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_picture`, `check_quality`, `check`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// A PulseAudio sink-input: one application's playback stream. Linux only;
/// Windows picks audio by process id from [`CaptureSource`] instead.
class AudioSource {
  final int index;
  final int sink;
  final String appName;
  final String binary;
  final String mediaName;

  const AudioSource({
    required this.index,
    required this.sink,
    required this.appName,
    required this.binary,
    required this.mediaName,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      sink.hashCode ^
      appName.hashCode ^
      binary.hashCode ^
      mediaName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioSource &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          sink == other.sink &&
          appName == other.appName &&
          binary == other.binary &&
          mediaName == other.mediaName;
}

/// A screen or window that can be captured.
class CaptureSource {
  final int index;
  final String title;

  /// Windows only: the owning process, for app-loopback audio capture.
  final int? audioSourcePid;

  /// Windows only: a minimised window. There is no picture of it until it
  /// is back on screen, so a share of it starts paused and begins when the
  /// user opens it.
  final bool minimised;

  const CaptureSource({
    required this.index,
    required this.title,
    this.audioSourcePid,
    required this.minimised,
  });

  @override
  int get hashCode =>
      index.hashCode ^
      title.hashCode ^
      audioSourcePid.hashCode ^
      minimised.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CaptureSource &&
          runtimeType == other.runtimeType &&
          index == other.index &&
          title == other.title &&
          audioSourcePid == other.audioSourcePid &&
          minimised == other.minimised;
}

class ScreenShareConfig {
  final String livekitUrl;
  final String livekitToken;

  /// Height cap in rows (720, 1080, ...). A smaller capture is not upscaled.
  final int resolution;
  final int fps;

  /// Megabits per second.
  final int bitrate;
  final bool shareAudio;
  final bool captureFullScreen;

  /// Index into `list_capture_sources` for the same `capture_full_screen`.
  final int? selectedVideoSourceIndex;
  final VideoCodec codec;
  final SharePriority priority;

  /// Linux: the PulseAudio sink-input to capture, and the sink it plays to.
  final int? selectedAudioSourceIndex;
  final int? selectedAudioSourceSink;

  /// Windows: the process whose audio to capture; none means the whole mix.
  final int? selectedAudioSourcePid;

  /// The channel key this call is encrypted with, and the LiveKit key-ring
  /// slot it occupies (ARCHITECTURE.md §5).
  ///
  /// A screen share is a second connection into the same encrypted room, so
  /// it has to encrypt with the same key as everything else. Publishing it in
  /// the clear would not fail — LiveKit skips the frame cryptor for a track
  /// that declares no encryption — it would simply hand the server the one
  /// stream nobody meant it to have.
  final Uint8List e2EeKey;
  final int e2EeKeyIndex;

  const ScreenShareConfig({
    required this.livekitUrl,
    required this.livekitToken,
    required this.resolution,
    required this.fps,
    required this.bitrate,
    required this.shareAudio,
    required this.captureFullScreen,
    this.selectedVideoSourceIndex,
    required this.codec,
    required this.priority,
    this.selectedAudioSourceIndex,
    this.selectedAudioSourceSink,
    this.selectedAudioSourcePid,
    required this.e2EeKey,
    required this.e2EeKeyIndex,
  });

  @override
  int get hashCode =>
      livekitUrl.hashCode ^
      livekitToken.hashCode ^
      resolution.hashCode ^
      fps.hashCode ^
      bitrate.hashCode ^
      shareAudio.hashCode ^
      captureFullScreen.hashCode ^
      selectedVideoSourceIndex.hashCode ^
      codec.hashCode ^
      priority.hashCode ^
      selectedAudioSourceIndex.hashCode ^
      selectedAudioSourceSink.hashCode ^
      selectedAudioSourcePid.hashCode ^
      e2EeKey.hashCode ^
      e2EeKeyIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScreenShareConfig &&
          runtimeType == other.runtimeType &&
          livekitUrl == other.livekitUrl &&
          livekitToken == other.livekitToken &&
          resolution == other.resolution &&
          fps == other.fps &&
          bitrate == other.bitrate &&
          shareAudio == other.shareAudio &&
          captureFullScreen == other.captureFullScreen &&
          selectedVideoSourceIndex == other.selectedVideoSourceIndex &&
          codec == other.codec &&
          priority == other.priority &&
          selectedAudioSourceIndex == other.selectedAudioSourceIndex &&
          selectedAudioSourceSink == other.selectedAudioSourceSink &&
          selectedAudioSourcePid == other.selectedAudioSourcePid &&
          e2EeKey == other.e2EeKey &&
          e2EeKeyIndex == other.e2EeKeyIndex;
}

/// Lifecycle events pushed from Rust up to Flutter.
enum ScreenshareEvent {
  /// The captured window was closed, so capture stopped at the source.
  /// Flutter should tear the session down and update its UI.
  sourceClosed,

  /// H264 was asked for and the GPU could not encode it, at the start or
  /// part way through, so the share went out as VP9 instead.
  encoderFellBack,
}

/// What a share gives up when the computer or the connection cannot keep up:
/// WebRTC's degradation preference, which LiveKit passes on as it is.
///
/// LiveKit's default for a screen share keeps the picture sharp and drops
/// frames, which suits text and slides and makes a game stutter. Rift starts
/// on [`SharePriority::Smoothness`], since a stream is usually something moving.
enum SharePriority {
  /// Keep the frame rate; the picture softens instead.
  smoothness,

  /// Give up a little of each.
  balanced,

  /// Keep the picture sharp; frames are dropped instead.
  sharpness,
}

/// What can change while a share is running: the picture's size and rate, and
/// whether its sound goes with it. The source, codec, bitrate and priority stay
/// as the share started.
class ShareQuality {
  /// Height cap in rows, as [`ScreenShareConfig::resolution`].
  final int resolution;
  final int fps;
  final bool shareAudio;

  const ShareQuality({
    required this.resolution,
    required this.fps,
    required this.shareAudio,
  });

  @override
  int get hashCode => resolution.hashCode ^ fps.hashCode ^ shareAudio.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShareQuality &&
          runtimeType == other.runtimeType &&
          resolution == other.resolution &&
          fps == other.fps &&
          shareAudio == other.shareAudio;
}

/// Codec for the published video track. The Dart settings store these same
/// names as strings, so the mapping there is by name.
enum VideoCodec { h264, vp8, vp9 }
