// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'api/audio_endpoints.dart';
import 'api/cue.dart';
import 'api/mic_test.dart';
import 'api/screenshare.dart';
import 'api/screenshare/types.dart';
import 'api/soundshare.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -697761063;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_rift',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Stream<void> crateApiAudioEndpointsAudioDeviceChanges();

  Future<String?> crateApiAudioEndpointsDefaultInputEndpoint();

  Future<String?> crateApiAudioEndpointsDefaultOutputEndpoint();

  Future<Uint8List?> crateApiScreenshareGetCaptureSourceThumbnail({
    required bool captureFullScreen,
    required int sourceIndex,
  });

  Future<void> crateApiInitApp();

  Future<List<AudioSource>> crateApiScreenshareListAudioSources();

  Future<List<CaptureSource>> crateApiScreenshareListCaptureSources({
    required bool captureFullScreen,
  });

  Future<List<AudioEndpoint>> crateApiAudioEndpointsListInputEndpoints();

  Future<List<AudioEndpoint>> crateApiAudioEndpointsListOutputEndpoints();

  Stream<Int16List> crateApiMicTestMicTestSamples({String? deviceId});

  Future<CueStarted> crateApiCuePlayCue({
    String? deviceId,
    required List<int> mp3,
    required double volume,
    required bool looping,
  });

  Stream<ScreenshareEvent> crateApiScreenshareScreenshareEventStream();

  Future<void> crateApiCueSetCueVolume({
    required int id,
    required double volume,
  });

  Stream<SoundShareEvent> crateApiSoundshareSoundShareEventStream();

  Future<String> crateApiScreenshareStartScreenshare({
    required ScreenShareConfig config,
  });

  Future<String> crateApiSoundshareStartSoundShare({
    required SoundShareConfig config,
  });

  Future<void> crateApiCueStopCue({required int id});

  Future<void> crateApiMicTestStopMicTest();

  Future<String> crateApiScreenshareStopScreenshare();

  Future<String> crateApiSoundshareStopSoundShare();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Stream<void> crateApiAudioEndpointsAudioDeviceChanges() {
    final sink = RustStreamSink<void>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_unit_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 1,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiAudioEndpointsAudioDeviceChangesConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiAudioEndpointsAudioDeviceChangesConstMeta =>
      const TaskConstMeta(
        debugName: 'audio_device_changes',
        argNames: ['sink'],
      );

  @override
  Future<String?> crateApiAudioEndpointsDefaultInputEndpoint() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioEndpointsDefaultInputEndpointConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioEndpointsDefaultInputEndpointConstMeta =>
      const TaskConstMeta(debugName: 'default_input_endpoint', argNames: []);

  @override
  Future<String?> crateApiAudioEndpointsDefaultOutputEndpoint() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioEndpointsDefaultOutputEndpointConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioEndpointsDefaultOutputEndpointConstMeta =>
      const TaskConstMeta(debugName: 'default_output_endpoint', argNames: []);

  @override
  Future<Uint8List?> crateApiScreenshareGetCaptureSourceThumbnail({
    required bool captureFullScreen,
    required int sourceIndex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(captureFullScreen, serializer);
          sse_encode_u_32(sourceIndex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScreenshareGetCaptureSourceThumbnailConstMeta,
        argValues: [captureFullScreen, sourceIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScreenshareGetCaptureSourceThumbnailConstMeta =>
      const TaskConstMeta(
        debugName: 'get_capture_source_thumbnail',
        argNames: ['captureFullScreen', 'sourceIndex'],
      );

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: 'init_app', argNames: []);

  @override
  Future<List<AudioSource>> crateApiScreenshareListAudioSources() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_source,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScreenshareListAudioSourcesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScreenshareListAudioSourcesConstMeta =>
      const TaskConstMeta(debugName: 'list_audio_sources', argNames: []);

  @override
  Future<List<CaptureSource>> crateApiScreenshareListCaptureSources({
    required bool captureFullScreen,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(captureFullScreen, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_capture_source,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiScreenshareListCaptureSourcesConstMeta,
        argValues: [captureFullScreen],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScreenshareListCaptureSourcesConstMeta =>
      const TaskConstMeta(
        debugName: 'list_capture_sources',
        argNames: ['captureFullScreen'],
      );

  @override
  Future<List<AudioEndpoint>> crateApiAudioEndpointsListInputEndpoints() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_endpoint,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioEndpointsListInputEndpointsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioEndpointsListInputEndpointsConstMeta =>
      const TaskConstMeta(debugName: 'list_input_endpoints', argNames: []);

  @override
  Future<List<AudioEndpoint>> crateApiAudioEndpointsListOutputEndpoints() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_audio_endpoint,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAudioEndpointsListOutputEndpointsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAudioEndpointsListOutputEndpointsConstMeta =>
      const TaskConstMeta(debugName: 'list_output_endpoints', argNames: []);

  @override
  Stream<Int16List> crateApiMicTestMicTestSamples({String? deviceId}) {
    final sink = RustStreamSink<Int16List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_opt_String(deviceId, serializer);
            sse_encode_StreamSink_list_prim_i_16_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiMicTestMicTestSamplesConstMeta,
          argValues: [deviceId, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiMicTestMicTestSamplesConstMeta =>
      const TaskConstMeta(
        debugName: 'mic_test_samples',
        argNames: ['deviceId', 'sink'],
      );

  @override
  Future<CueStarted> crateApiCuePlayCue({
    String? deviceId,
    required List<int> mp3,
    required double volume,
    required bool looping,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(deviceId, serializer);
          sse_encode_list_prim_u_8_loose(mp3, serializer);
          sse_encode_f_32(volume, serializer);
          sse_encode_bool(looping, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_cue_started,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCuePlayCueConstMeta,
        argValues: [deviceId, mp3, volume, looping],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCuePlayCueConstMeta => const TaskConstMeta(
    debugName: 'play_cue',
    argNames: ['deviceId', 'mp3', 'volume', 'looping'],
  );

  @override
  Stream<ScreenshareEvent> crateApiScreenshareScreenshareEventStream() {
    final sink = RustStreamSink<ScreenshareEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_screenshare_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 12,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiScreenshareScreenshareEventStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiScreenshareScreenshareEventStreamConstMeta =>
      const TaskConstMeta(
        debugName: 'screenshare_event_stream',
        argNames: ['sink'],
      );

  @override
  Future<void> crateApiCueSetCueVolume({
    required int id,
    required double volume,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          sse_encode_f_32(volume, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCueSetCueVolumeConstMeta,
        argValues: [id, volume],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCueSetCueVolumeConstMeta => const TaskConstMeta(
    debugName: 'set_cue_volume',
    argNames: ['id', 'volume'],
  );

  @override
  Stream<SoundShareEvent> crateApiSoundshareSoundShareEventStream() {
    final sink = RustStreamSink<SoundShareEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_sound_share_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 14,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiSoundshareSoundShareEventStreamConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiSoundshareSoundShareEventStreamConstMeta =>
      const TaskConstMeta(
        debugName: 'sound_share_event_stream',
        argNames: ['sink'],
      );

  @override
  Future<String> crateApiScreenshareStartScreenshare({
    required ScreenShareConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_screen_share_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScreenshareStartScreenshareConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScreenshareStartScreenshareConstMeta =>
      const TaskConstMeta(debugName: 'start_screenshare', argNames: ['config']);

  @override
  Future<String> crateApiSoundshareStartSoundShare({
    required SoundShareConfig config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_sound_share_config(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSoundshareStartSoundShareConstMeta,
        argValues: [config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSoundshareStartSoundShareConstMeta =>
      const TaskConstMeta(debugName: 'start_sound_share', argNames: ['config']);

  @override
  Future<void> crateApiCueStopCue({required int id}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(id, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCueStopCueConstMeta,
        argValues: [id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCueStopCueConstMeta =>
      const TaskConstMeta(debugName: 'stop_cue', argNames: ['id']);

  @override
  Future<void> crateApiMicTestStopMicTest() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMicTestStopMicTestConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMicTestStopMicTestConstMeta =>
      const TaskConstMeta(debugName: 'stop_mic_test', argNames: []);

  @override
  Future<String> crateApiScreenshareStopScreenshare() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScreenshareStopScreenshareConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScreenshareStopScreenshareConstMeta =>
      const TaskConstMeta(debugName: 'stop_screenshare', argNames: []);

  @override
  Future<String> crateApiSoundshareStopSoundShare() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSoundshareStopSoundShareConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSoundshareStopSoundShareConstMeta =>
      const TaskConstMeta(debugName: 'stop_sound_share', argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Int16List> dco_decode_StreamSink_list_prim_i_16_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<ScreenshareEvent> dco_decode_StreamSink_screenshare_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<SoundShareEvent> dco_decode_StreamSink_sound_share_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<void> dco_decode_StreamSink_unit_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AudioEndpoint dco_decode_audio_endpoint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AudioEndpoint(
      deviceId: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      channels: dco_decode_u_32(arr[2]),
      sampleRate: dco_decode_u_32(arr[3]),
      opens: dco_decode_bool(arr[4]),
    );
  }

  @protected
  AudioSource dco_decode_audio_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AudioSource(
      index: dco_decode_u_32(arr[0]),
      sink: dco_decode_u_32(arr[1]),
      appName: dco_decode_String(arr[2]),
      binary: dco_decode_String(arr[3]),
      mediaName: dco_decode_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ScreenShareConfig dco_decode_box_autoadd_screen_share_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_screen_share_config(raw);
  }

  @protected
  SoundShareConfig dco_decode_box_autoadd_sound_share_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sound_share_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CaptureSource dco_decode_capture_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return CaptureSource(
      index: dco_decode_u_32(arr[0]),
      title: dco_decode_String(arr[1]),
      audioSourcePid: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  CueStarted dco_decode_cue_started(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return CueStarted(
      id: dco_decode_u_32(arr[0]),
      durationMs: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<AudioEndpoint> dco_decode_list_audio_endpoint(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audio_endpoint).toList();
  }

  @protected
  List<AudioSource> dco_decode_list_audio_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_audio_source).toList();
  }

  @protected
  List<CaptureSource> dco_decode_list_capture_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_capture_source).toList();
  }

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int16List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  ScreenShareConfig dco_decode_screen_share_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return ScreenShareConfig(
      livekitUrl: dco_decode_String(arr[0]),
      livekitToken: dco_decode_String(arr[1]),
      resolution: dco_decode_u_32(arr[2]),
      fps: dco_decode_u_32(arr[3]),
      bitrate: dco_decode_u_32(arr[4]),
      shareAudio: dco_decode_bool(arr[5]),
      captureFullScreen: dco_decode_bool(arr[6]),
      selectedVideoSourceIndex: dco_decode_opt_box_autoadd_u_32(arr[7]),
      codec: dco_decode_video_codec(arr[8]),
      selectedAudioSourceIndex: dco_decode_opt_box_autoadd_u_32(arr[9]),
      selectedAudioSourceSink: dco_decode_opt_box_autoadd_u_32(arr[10]),
      selectedAudioSourcePid: dco_decode_opt_box_autoadd_u_32(arr[11]),
      e2EeKey: dco_decode_list_prim_u_8_strict(arr[12]),
      e2EeKeyIndex: dco_decode_i_32(arr[13]),
    );
  }

  @protected
  ScreenshareEvent dco_decode_screenshare_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ScreenshareEvent.values[raw as int];
  }

  @protected
  SoundShareConfig dco_decode_sound_share_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return SoundShareConfig(
      livekitUrl: dco_decode_String(arr[0]),
      livekitToken: dco_decode_String(arr[1]),
      selectedAudioSourceIndex: dco_decode_opt_box_autoadd_u_32(arr[2]),
      selectedAudioSourceSink: dco_decode_opt_box_autoadd_u_32(arr[3]),
      selectedAudioSourcePid: dco_decode_opt_box_autoadd_u_32(arr[4]),
      sourceLabel: dco_decode_String(arr[5]),
      e2EeKey: dco_decode_list_prim_u_8_strict(arr[6]),
      e2EeKeyIndex: dco_decode_i_32(arr[7]),
    );
  }

  @protected
  SoundShareEvent dco_decode_sound_share_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SoundShareEvent.values[raw as int];
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VideoCodec dco_decode_video_codec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VideoCodec.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Int16List> sse_decode_StreamSink_list_prim_i_16_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<ScreenshareEvent> sse_decode_StreamSink_screenshare_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<SoundShareEvent> sse_decode_StreamSink_sound_share_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<void> sse_decode_StreamSink_unit_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AudioEndpoint sse_decode_audio_endpoint(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_deviceId = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_channels = sse_decode_u_32(deserializer);
    var var_sampleRate = sse_decode_u_32(deserializer);
    var var_opens = sse_decode_bool(deserializer);
    return AudioEndpoint(
      deviceId: var_deviceId,
      name: var_name,
      channels: var_channels,
      sampleRate: var_sampleRate,
      opens: var_opens,
    );
  }

  @protected
  AudioSource sse_decode_audio_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_sink = sse_decode_u_32(deserializer);
    var var_appName = sse_decode_String(deserializer);
    var var_binary = sse_decode_String(deserializer);
    var var_mediaName = sse_decode_String(deserializer);
    return AudioSource(
      index: var_index,
      sink: var_sink,
      appName: var_appName,
      binary: var_binary,
      mediaName: var_mediaName,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ScreenShareConfig sse_decode_box_autoadd_screen_share_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_screen_share_config(deserializer));
  }

  @protected
  SoundShareConfig sse_decode_box_autoadd_sound_share_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sound_share_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CaptureSource sse_decode_capture_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_index = sse_decode_u_32(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_audioSourcePid = sse_decode_opt_box_autoadd_u_32(deserializer);
    return CaptureSource(
      index: var_index,
      title: var_title,
      audioSourcePid: var_audioSourcePid,
    );
  }

  @protected
  CueStarted sse_decode_cue_started(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_durationMs = sse_decode_u_32(deserializer);
    return CueStarted(id: var_id, durationMs: var_durationMs);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<AudioEndpoint> sse_decode_list_audio_endpoint(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AudioEndpoint>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audio_endpoint(deserializer));
    }
    return ans_;
  }

  @protected
  List<AudioSource> sse_decode_list_audio_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AudioSource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_audio_source(deserializer));
    }
    return ans_;
  }

  @protected
  List<CaptureSource> sse_decode_list_capture_source(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CaptureSource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_capture_source(deserializer));
    }
    return ans_;
  }

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ScreenShareConfig sse_decode_screen_share_config(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_livekitUrl = sse_decode_String(deserializer);
    var var_livekitToken = sse_decode_String(deserializer);
    var var_resolution = sse_decode_u_32(deserializer);
    var var_fps = sse_decode_u_32(deserializer);
    var var_bitrate = sse_decode_u_32(deserializer);
    var var_shareAudio = sse_decode_bool(deserializer);
    var var_captureFullScreen = sse_decode_bool(deserializer);
    var var_selectedVideoSourceIndex = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_codec = sse_decode_video_codec(deserializer);
    var var_selectedAudioSourceIndex = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_selectedAudioSourceSink = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_selectedAudioSourcePid = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_e2EeKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_e2EeKeyIndex = sse_decode_i_32(deserializer);
    return ScreenShareConfig(
      livekitUrl: var_livekitUrl,
      livekitToken: var_livekitToken,
      resolution: var_resolution,
      fps: var_fps,
      bitrate: var_bitrate,
      shareAudio: var_shareAudio,
      captureFullScreen: var_captureFullScreen,
      selectedVideoSourceIndex: var_selectedVideoSourceIndex,
      codec: var_codec,
      selectedAudioSourceIndex: var_selectedAudioSourceIndex,
      selectedAudioSourceSink: var_selectedAudioSourceSink,
      selectedAudioSourcePid: var_selectedAudioSourcePid,
      e2EeKey: var_e2EeKey,
      e2EeKeyIndex: var_e2EeKeyIndex,
    );
  }

  @protected
  ScreenshareEvent sse_decode_screenshare_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ScreenshareEvent.values[inner];
  }

  @protected
  SoundShareConfig sse_decode_sound_share_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_livekitUrl = sse_decode_String(deserializer);
    var var_livekitToken = sse_decode_String(deserializer);
    var var_selectedAudioSourceIndex = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_selectedAudioSourceSink = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_selectedAudioSourcePid = sse_decode_opt_box_autoadd_u_32(
      deserializer,
    );
    var var_sourceLabel = sse_decode_String(deserializer);
    var var_e2EeKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_e2EeKeyIndex = sse_decode_i_32(deserializer);
    return SoundShareConfig(
      livekitUrl: var_livekitUrl,
      livekitToken: var_livekitToken,
      selectedAudioSourceIndex: var_selectedAudioSourceIndex,
      selectedAudioSourceSink: var_selectedAudioSourceSink,
      selectedAudioSourcePid: var_selectedAudioSourcePid,
      sourceLabel: var_sourceLabel,
      e2EeKey: var_e2EeKey,
      e2EeKeyIndex: var_e2EeKeyIndex,
    );
  }

  @protected
  SoundShareEvent sse_decode_sound_share_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SoundShareEvent.values[inner];
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VideoCodec sse_decode_video_codec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return VideoCodec.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_list_prim_i_16_strict_Sse(
    RustStreamSink<Int16List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_i_16_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_screenshare_event_Sse(
    RustStreamSink<ScreenshareEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_screenshare_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_sound_share_event_Sse(
    RustStreamSink<SoundShareEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_sound_share_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_unit_Sse(
    RustStreamSink<void> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_audio_endpoint(AudioEndpoint self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.deviceId, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.channels, serializer);
    sse_encode_u_32(self.sampleRate, serializer);
    sse_encode_bool(self.opens, serializer);
  }

  @protected
  void sse_encode_audio_source(AudioSource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_u_32(self.sink, serializer);
    sse_encode_String(self.appName, serializer);
    sse_encode_String(self.binary, serializer);
    sse_encode_String(self.mediaName, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_screen_share_config(
    ScreenShareConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_screen_share_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sound_share_config(
    SoundShareConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sound_share_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_capture_source(CaptureSource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.index, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_opt_box_autoadd_u_32(self.audioSourcePid, serializer);
  }

  @protected
  void sse_encode_cue_started(CueStarted self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_u_32(self.durationMs, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_audio_endpoint(
    List<AudioEndpoint> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audio_endpoint(item, serializer);
    }
  }

  @protected
  void sse_encode_list_audio_source(
    List<AudioSource> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_audio_source(item, serializer);
    }
  }

  @protected
  void sse_encode_list_capture_source(
    List<CaptureSource> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_capture_source(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_screen_share_config(
    ScreenShareConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.livekitUrl, serializer);
    sse_encode_String(self.livekitToken, serializer);
    sse_encode_u_32(self.resolution, serializer);
    sse_encode_u_32(self.fps, serializer);
    sse_encode_u_32(self.bitrate, serializer);
    sse_encode_bool(self.shareAudio, serializer);
    sse_encode_bool(self.captureFullScreen, serializer);
    sse_encode_opt_box_autoadd_u_32(self.selectedVideoSourceIndex, serializer);
    sse_encode_video_codec(self.codec, serializer);
    sse_encode_opt_box_autoadd_u_32(self.selectedAudioSourceIndex, serializer);
    sse_encode_opt_box_autoadd_u_32(self.selectedAudioSourceSink, serializer);
    sse_encode_opt_box_autoadd_u_32(self.selectedAudioSourcePid, serializer);
    sse_encode_list_prim_u_8_strict(self.e2EeKey, serializer);
    sse_encode_i_32(self.e2EeKeyIndex, serializer);
  }

  @protected
  void sse_encode_screenshare_event(
    ScreenshareEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sound_share_config(
    SoundShareConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.livekitUrl, serializer);
    sse_encode_String(self.livekitToken, serializer);
    sse_encode_opt_box_autoadd_u_32(self.selectedAudioSourceIndex, serializer);
    sse_encode_opt_box_autoadd_u_32(self.selectedAudioSourceSink, serializer);
    sse_encode_opt_box_autoadd_u_32(self.selectedAudioSourcePid, serializer);
    sse_encode_String(self.sourceLabel, serializer);
    sse_encode_list_prim_u_8_strict(self.e2EeKey, serializer);
    sse_encode_i_32(self.e2EeKeyIndex, serializer);
  }

  @protected
  void sse_encode_sound_share_event(
    SoundShareEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_video_codec(VideoCodec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
