// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

import 'api/audio_endpoints.dart';
import 'api/cue.dart';
import 'api/mic_test.dart';
import 'api/noise_filter.dart';
import 'api/screenshare.dart';
import 'api/screenshare/types.dart';
import 'api/soundshare.dart';
import 'api/toast.dart';
import 'api/updater.dart';
import 'frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<int> dco_decode_StreamSink_i_32_Sse(dynamic raw);

  @protected
  RustStreamSink<Int16List> dco_decode_StreamSink_list_prim_i_16_strict_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ScreenshareEvent> dco_decode_StreamSink_screenshare_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SoundShareEvent> dco_decode_StreamSink_sound_share_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<void> dco_decode_StreamSink_unit_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioEndpoint dco_decode_audio_endpoint(dynamic raw);

  @protected
  AudioSource dco_decode_audio_source(dynamic raw);

  @protected
  AvailableUpdate dco_decode_available_update(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AvailableUpdate dco_decode_box_autoadd_available_update(dynamic raw);

  @protected
  ScreenShareConfig dco_decode_box_autoadd_screen_share_config(dynamic raw);

  @protected
  ShareQuality dco_decode_box_autoadd_share_quality(dynamic raw);

  @protected
  SoundShareConfig dco_decode_box_autoadd_sound_share_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CaptureSource dco_decode_capture_source(dynamic raw);

  @protected
  CueStarted dco_decode_cue_started(dynamic raw);

  @protected
  DeepFilterEntry dco_decode_deep_filter_entry(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<AudioEndpoint> dco_decode_list_audio_endpoint(dynamic raw);

  @protected
  List<AudioSource> dco_decode_list_audio_source(dynamic raw);

  @protected
  List<CaptureSource> dco_decode_list_capture_source(dynamic raw);

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<VideoCodec> dco_decode_list_video_codec(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AvailableUpdate? dco_decode_opt_box_autoadd_available_update(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  ScreenShareConfig dco_decode_screen_share_config(dynamic raw);

  @protected
  ScreenshareEvent dco_decode_screenshare_event(dynamic raw);

  @protected
  SharePriority dco_decode_share_priority(dynamic raw);

  @protected
  ShareQuality dco_decode_share_quality(dynamic raw);

  @protected
  SoundShareConfig dco_decode_sound_share_config(dynamic raw);

  @protected
  SoundShareEvent dco_decode_sound_share_event(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VideoCodec dco_decode_video_codec(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<int> sse_decode_StreamSink_i_32_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Int16List> sse_decode_StreamSink_list_prim_i_16_strict_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ScreenshareEvent> sse_decode_StreamSink_screenshare_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SoundShareEvent> sse_decode_StreamSink_sound_share_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<void> sse_decode_StreamSink_unit_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioEndpoint sse_decode_audio_endpoint(SseDeserializer deserializer);

  @protected
  AudioSource sse_decode_audio_source(SseDeserializer deserializer);

  @protected
  AvailableUpdate sse_decode_available_update(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AvailableUpdate sse_decode_box_autoadd_available_update(
    SseDeserializer deserializer,
  );

  @protected
  ScreenShareConfig sse_decode_box_autoadd_screen_share_config(
    SseDeserializer deserializer,
  );

  @protected
  ShareQuality sse_decode_box_autoadd_share_quality(
    SseDeserializer deserializer,
  );

  @protected
  SoundShareConfig sse_decode_box_autoadd_sound_share_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CaptureSource sse_decode_capture_source(SseDeserializer deserializer);

  @protected
  CueStarted sse_decode_cue_started(SseDeserializer deserializer);

  @protected
  DeepFilterEntry sse_decode_deep_filter_entry(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<AudioEndpoint> sse_decode_list_audio_endpoint(
    SseDeserializer deserializer,
  );

  @protected
  List<AudioSource> sse_decode_list_audio_source(SseDeserializer deserializer);

  @protected
  List<CaptureSource> sse_decode_list_capture_source(
    SseDeserializer deserializer,
  );

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<VideoCodec> sse_decode_list_video_codec(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AvailableUpdate? sse_decode_opt_box_autoadd_available_update(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  ScreenShareConfig sse_decode_screen_share_config(
    SseDeserializer deserializer,
  );

  @protected
  ScreenshareEvent sse_decode_screenshare_event(SseDeserializer deserializer);

  @protected
  SharePriority sse_decode_share_priority(SseDeserializer deserializer);

  @protected
  ShareQuality sse_decode_share_quality(SseDeserializer deserializer);

  @protected
  SoundShareConfig sse_decode_sound_share_config(SseDeserializer deserializer);

  @protected
  SoundShareEvent sse_decode_sound_share_event(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VideoCodec sse_decode_video_codec(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_i_32_Sse(
    RustStreamSink<int> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_list_prim_i_16_strict_Sse(
    RustStreamSink<Int16List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_screenshare_event_Sse(
    RustStreamSink<ScreenshareEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sound_share_event_Sse(
    RustStreamSink<SoundShareEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_unit_Sse(
    RustStreamSink<void> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_endpoint(AudioEndpoint self, SseSerializer serializer);

  @protected
  void sse_encode_audio_source(AudioSource self, SseSerializer serializer);

  @protected
  void sse_encode_available_update(
    AvailableUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_available_update(
    AvailableUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_screen_share_config(
    ScreenShareConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_share_quality(
    ShareQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sound_share_config(
    SoundShareConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_capture_source(CaptureSource self, SseSerializer serializer);

  @protected
  void sse_encode_cue_started(CueStarted self, SseSerializer serializer);

  @protected
  void sse_encode_deep_filter_entry(
    DeepFilterEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_endpoint(
    List<AudioEndpoint> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_audio_source(
    List<AudioSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_capture_source(
    List<CaptureSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_16_strict(
    Int16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_video_codec(
    List<VideoCodec> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_available_update(
    AvailableUpdate? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_screen_share_config(
    ScreenShareConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_screenshare_event(
    ScreenshareEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_share_priority(SharePriority self, SseSerializer serializer);

  @protected
  void sse_encode_share_quality(ShareQuality self, SseSerializer serializer);

  @protected
  void sse_encode_sound_share_config(
    SoundShareConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sound_share_event(
    SoundShareEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_video_codec(VideoCodec self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
