// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/screenshare.dart';
import 'api/screenshare/audio_linux.dart';
import 'api/screenshare/audio_windows.dart';
import 'api/screenshare/capture.dart';
import 'api/screenshare/types.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioSource dco_decode_audio_source(dynamic raw);

  @protected
  AudioSourceWindows dco_decode_audio_source_windows(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ScreenShareConfig dco_decode_box_autoadd_screen_share_config(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CaptureSource dco_decode_capture_source(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<AudioSource> dco_decode_list_audio_source(dynamic raw);

  @protected
  List<AudioSourceWindows> dco_decode_list_audio_source_windows(dynamic raw);

  @protected
  List<CaptureSource> dco_decode_list_capture_source(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  ScreenShareConfig dco_decode_screen_share_config(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioSource sse_decode_audio_source(SseDeserializer deserializer);

  @protected
  AudioSourceWindows sse_decode_audio_source_windows(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ScreenShareConfig sse_decode_box_autoadd_screen_share_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CaptureSource sse_decode_capture_source(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<AudioSource> sse_decode_list_audio_source(SseDeserializer deserializer);

  @protected
  List<AudioSourceWindows> sse_decode_list_audio_source_windows(
    SseDeserializer deserializer,
  );

  @protected
  List<CaptureSource> sse_decode_list_capture_source(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ScreenShareConfig sse_decode_screen_share_config(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_source(AudioSource self, SseSerializer serializer);

  @protected
  void sse_encode_audio_source_windows(
    AudioSourceWindows self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_screen_share_config(
    ScreenShareConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_capture_source(CaptureSource self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_source(
    List<AudioSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_audio_source_windows(
    List<AudioSourceWindows> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_capture_source(
    List<CaptureSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_screen_share_config(
    ScreenShareConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
