// Regenerate `test/wire_vectors.json` from the current implementation.
//
//   dart run tool/gen_wire_vectors.dart
//
// Run this only when the format is *meant* to change. The vectors catch drift,
// so regenerating them to make a failing test pass is regenerating the thing
// that was telling you something.
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:rift_crypto/rift_crypto.dart';

final crypto = CryptoRepository();

/// A fixed seed, so the vectors are reproducible. 32 bytes of 0x01..0x20.
final seed = Uint8List.fromList(List.generate(32, (i) => i + 1));

Future<void> main() async {
  final server = await crypto.deriveServerIdentity(
    masterSeed: seed,
    host: 'rift.example',
    serverId: '11111111-2222-4333-8444-555555555555',
  );
  final central = await crypto.deriveServerIdentity(
    masterSeed: seed,
    host: 'central.example',
  );
  final chat = await crypto.deriveChatIdentity(
    masterSeed: seed,
    host: 'rift.example',
  );

  // A fixed key, sealed to the fixed chat identity. The ephemeral half of the
  // wrap is random, so this blob cannot be regenerated deterministically — it
  // is *frozen*, and a port proves itself by opening it rather than by
  // producing the same bytes. That is the right test anyway: unwrapping is the
  // half a bot actually does.
  final wrappedKey = Uint8List.fromList(List.generate(32, (i) => 0xA0 ^ i));
  final wrapped = await crypto.wrapKey(
    key: wrappedKey,
    recipientPublicKey: chat.publicKeyBytes,
  );

  // What a bot encrypts its media with, derived from a channel key it is never
  // given (BOTS.md §6b). Members compute this; the bot only receives it.
  const botId = '99999999-8888-4777-8666-555555555555';
  final botVoiceKey = await crypto.hmacSha256(
    key: wrappedKey,
    message: 'voicebot:v1:$botId',
  );

  // A DM key, from the fixed chat identity to a fixed peer. Both ends derive
  // the same bytes from opposite halves of the exchange, so the vector holds
  // the peer's *public* key and the answer — which is what a port has to match.
  final peerChat = await crypto.deriveChatIdentity(
    masterSeed: Uint8List.fromList(List.generate(32, (i) => 0x40 + i)),
    host: 'rift.example',
  );
  final dmKey = await crypto.deriveDmKey(
    myKeyPair: chat.keyPair,
    theirPublicKey: peerChat.publicKeyBytes,
  );

  final vectors = {
    'note':
        'Generated by tool/gen_wire_vectors.dart. See WIRE.md. These freeze '
        'the format so a second implementation can match it — they do not '
        'prove the format was right, only that it has not moved.',
    'seed_base64': CryptoRepository.toBase64(seed),
    'hmac': {
      'vault_key': CryptoRepository.toBase64(
        await crypto.hmacSha256(key: seed, message: 'vault:v1'),
      ),
      'context_rift.example:11111111-2222-4333-8444-555555555555:v1':
          CryptoRepository.toBase64(
            await crypto.hmacSha256(
              key: seed,
              message: 'rift.example:11111111-2222-4333-8444-555555555555:v1',
            ),
          ),
    },
    'server_identity': {
      'host': 'rift.example',
      'server_id': '11111111-2222-4333-8444-555555555555',
      'public_key_base64': CryptoRepository.toBase64(server.publicKeyBytes),
      'public_key_base58': CryptoRepository.toBase58(server.publicKeyBytes),
      'stable_id': server.stableId,
    },
    'central_identity': {
      'host': 'central.example',
      'public_key_base64': CryptoRepository.toBase64(central.publicKeyBytes),
      'stable_id': central.stableId,
    },
    'chat_identity': {
      'host': 'rift.example',
      'public_key_base64': CryptoRepository.toBase64(chat.publicKeyBytes),
    },
    // `wrap:v1` — ARCHITECTURE.md §4. The plaintext inside the envelope is the
    // key's *base64*, not its bytes, because the Dart side seals a string. A
    // port that decodes once gets 44 bytes of ASCII where it wanted 32.
    'wrapped_key': {
      'note': 'unwraps to key_base64 with chat_identity’s private key',
      'key_base64': CryptoRepository.toBase64(wrappedKey),
      'ephemeral_public_key': wrapped.ephemeralPublicKey,
      'ciphertext': wrapped.ciphertext,
      'nonce': wrapped.nonce,
    },
    'bot_voice_key': {
      'note': 'HMAC-SHA256(wrapped_key.key, "voicebot:v1:<bot_id>")',
      'bot_id': botId,
      'key_base64': CryptoRepository.toBase64(botVoiceKey),
    },
    // `dm:v1` — ARCHITECTURE.md §4. The one key a bot derives rather than is
    // given, and the only chat crypto it does (BOTS.md §3).
    'dm_key': {
      'note': 'HMAC-SHA256(X25519(chat_identity, peer_chat_public_key), "dm:v1")',
      'peer_chat_public_key': CryptoRepository.toBase64(peerChat.publicKeyBytes),
      'key_base64': CryptoRepository.toBase64(dmKey),
    },
    'signed_payload': {
      'channel': MessageEnvelope.signedPayload(
        contextId: 'aaaa1111-0000-4000-8000-000000000001',
        keyVersion: 3,
        nonce: 'bm9uY2U=',
        ciphertext: 'Y2lwaGVy',
      ),
      'bot_plaintext': MessageEnvelope.signedPayload(
        contextId: 'aaaa1111-0000-4000-8000-000000000001',
        keyVersion: 0,
        nonce: '',
        ciphertext: '/echo hello',
      ),
      'dm_context': MessageEnvelope.conversationContext(
        'ffffffff-0000-4000-8000-000000000002',
        '00000000-0000-4000-8000-000000000001',
      ),
    },
    // Ed25519 is deterministic, so a signature is a vector like any other.
    // This is the one line that proves a port's key ladder *and* its payload
    // construction at once: get either wrong and the bytes differ.
    'signature': {
      'over': 'signed_payload.channel, by server_identity',
      'base64': CryptoRepository.toBase64(
        Uint8List.fromList(
          (await Ed25519().sign(
            utf8.encode(
              MessageEnvelope.signedPayload(
                contextId: 'aaaa1111-0000-4000-8000-000000000001',
                keyVersion: 3,
                nonce: 'bm9uY2U=',
                ciphertext: 'Y2lwaGVy',
              ),
            ),
            keyPair: server.keyPair,
          )).bytes,
        ),
      ),
    },
  };

  // Regenerating always shows a diff in `wrapped_key`, and only there. Sealing
  // picks a fresh ephemeral keypair and nonce every run, so that vector is a
  // different valid seal each time rather than a moving format — the test opens
  // it and checks what falls out. Every other vector is a derivation and is
  // byte-stable, which is what makes them worth freezing. Revert the
  // `wrapped_key` churn unless the format itself actually changed.
  final json = '${const JsonEncoder.withIndent('  ').convert(vectors)}\n';

  final file = File('test/wire_vectors.json');
  file.writeAsStringSync(json);
  stdout.writeln('wrote ${file.path}');

  // And the TypeScript SDK's copy, in the sibling repository.
  //
  // Written here rather than left to a sync script, because the two must not be
  // refreshable apart. The SDK used to read this repo's copy by relative
  // path; now that it is its own repository it vendors one, and a vendored
  // contract that can go stale is worse than no vectors at all — the SDK would
  // go on passing against a format nobody uses.
  //
  // Absent when somebody has only cloned this repo, which is ordinary and not a
  // failure. It says so rather than passing in silence, because the case that
  // matters is a format change made by somebody who has both and forgot one.
  final sdk = File('../rift-bot-sdk/test/wire_vectors.json');
  if (sdk.parent.existsSync()) {
    sdk.writeAsStringSync(json);
    stdout.writeln('wrote ${sdk.path}');
    stdout.writeln('  now run its tests: (cd ../rift-bot-sdk && npm test)');
  } else {
    stdout.writeln(
      'note: ../rift-bot-sdk is not checked out beside this repo, so its copy\n'
      '      was not updated. Refresh it before releasing an SDK built on this.',
    );
  }
}
