/// The top-level domains a bare word is allowed to be a link under.
///
/// A word with no `http://` in front of it has to be guessed at from its
/// shape, and chat is full of dotted words that are not addresses:
/// `main.dart`, `config.yml`, `v2.0`, `node.js`. So a bare word links only
/// when its last part is one of these, or it starts with `www.` — which
/// catches `flutter.dev` and `joinrift.app` and leaves the filenames alone.
/// Exotic domains get pasted with their scheme anyway.
///
/// One place, so extending it is a line.
const Set<String> linkTopLevelDomains = {
  'com',
  'org',
  'net',
  'edu',
  'gov',
  'mil',
  'int',
  'io',
  'dev',
  'app',
  'ai',
  'co',
  'me',
  'so',
  'sh',
  'gg',
  'tv',
  'fm',
  'xyz',
  'info',
  'biz',
  'site',
  'online',
  'tech',
  'cloud',
  'page',
  'news',
  'uk',
  'de',
  'fr',
  'nl',
  'es',
  'it',
  'pl',
  'se',
  'no',
  'fi',
  'dk',
  'ch',
  'at',
  'be',
  'ie',
  'pt',
  'cz',
  'ru',
  'ua',
  'tr',
  'in',
  'pk',
  'jp',
  'kr',
  'cn',
  'hk',
  'sg',
  'au',
  'nz',
  'ca',
  'us',
  'mx',
  'br',
  'ar',
  'za',
  'eu',
};
