#!/usr/bin/env bash
# Regenerates the licence notices for the native library into assets/licenses/.
#
#   rust_crates.txt   every crate compiled in (cargo-about, rust/about.toml),
#                     plus the NOTICE files Apache-2.0 asks to be passed on
#   libwebrtc.txt     the prebuilt WebRTC that livekit links, with the 27 or so
#                     projects inside it (boringssl, opus, libvpx, ffmpeg, ...)
#
# Run after a dependency bump, once the native library has been built so the
# WebRTC download is in rust/target. Needs `cargo install cargo-about
# --locked --features cli`.
set -euo pipefail

root="$(cd "$(dirname "$0")/.." && pwd)"
out="$root/assets/licenses"
registry="${CARGO_HOME:-$HOME/.cargo}/registry/src"
cd "$root/rust"

# ── Crates ──────────────────────────────────────────────
cargo about generate -c about.toml about.hbs -o "$out/rust_crates.txt"

# Apache-2.0 §4(d): a NOTICE shipped by a crate travels with it. Only crates
# that end up in the library — cfg_aliases has one too, but it is a build
# script dependency.
for crate in webrtc-sys; do
  version=$(awk -v n="$crate" '$0 == "name = \"" n "\"" {getline; gsub(/version = |"/, ""); print}' Cargo.lock)
  for notice in "$registry"/*/"$crate-$version"/NOTICE*; do
    [ -f "$notice" ] || continue
    printf '\n%s\nNOTICE from %s %s\n\n' "$(printf '=%.0s' {1..80})" "$crate" "$version" >> "$out/rust_crates.txt"
    cat "$notice" >> "$out/rust_crates.txt"
  done
done

# ── libwebrtc ───────────────────────────────────────────
# The tag webrtc-sys downloads is a constant in webrtc-sys-build; the licence
# file sits beside the library it downloaded.
build_version=$(awk '$0 == "name = \"webrtc-sys-build\"" {getline; gsub(/version = |"/, ""); print}' Cargo.lock)
tag=$(grep -h -o 'WEBRTC_TAG: &str = "[^"]*"' "$registry"/*/"webrtc-sys-build-$build_version"/src/lib.rs | cut -d'"' -f2)
licence=$(ls -t target/*/build/scratch-*/out/livekit_webrtc/livekit/*-"$tag"/*/LICENSE.md 2>/dev/null | head -1 || true)
if [ -z "$licence" ]; then
  echo "No LICENSE.md for $tag under rust/target — build the native library first." >&2
  exit 1
fi
{
  printf 'Licences for the prebuilt WebRTC (%s) linked into Rift'"'"'s native library\n' "$tag"
  printf 'by the livekit crate. Generated by scripts/generate_licenses.sh.\n\n'
  # The file ships HTML-escaped.
  python3 -c 'import html, sys; sys.stdout.write(html.unescape(open(sys.argv[1]).read()))' "$licence"
} > "$out/libwebrtc.txt"

echo "Wrote $out/rust_crates.txt and $out/libwebrtc.txt ($tag)"
