// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Every active render endpoint. Empty off Windows, and empty rather than
/// failing if the audio service cannot be reached: callers treat "nothing
/// known" as "do not filter", which keeps a broken probe from hiding devices
/// that would have worked.
Future<List<AudioEndpoint>> listOutputEndpoints() =>
    RustLib.instance.api.crateApiAudioEndpointsListOutputEndpoints();

/// Every active capture endpoint. See [`list_output_endpoints`].
Future<List<AudioEndpoint>> listInputEndpoints() =>
    RustLib.instance.api.crateApiAudioEndpointsListInputEndpoints();

/// One endpoint, and the format Windows hands a shared-mode client for it.
class AudioEndpoint {
  /// The endpoint id, in the same form WebRTC reports as a device's guid, so
  /// the two lists can be matched up.
  final String deviceId;
  final String name;
  final int channels;
  final int sampleRate;

  const AudioEndpoint({
    required this.deviceId,
    required this.name,
    required this.channels,
    required this.sampleRate,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      name.hashCode ^
      channels.hashCode ^
      sampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioEndpoint &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          name == other.name &&
          channels == other.channels &&
          sampleRate == other.sampleRate;
}
