// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Every active render endpoint. Empty off Windows, and empty rather than
/// failing if the audio service cannot be reached: callers treat "nothing
/// known" as "do not filter", which keeps a broken probe from hiding devices
/// that would have worked.
Future<List<AudioEndpoint>> listOutputEndpoints() =>
    RustLib.instance.api.crateApiAudioEndpointsListOutputEndpoints();

/// Every active capture endpoint. See [`list_output_endpoints`].
Future<List<AudioEndpoint>> listInputEndpoints() =>
    RustLib.instance.api.crateApiAudioEndpointsListInputEndpoints();

/// The id of the render endpoint Windows plays to by default, in the same
/// form as [`AudioEndpoint::device_id`]. None off Windows, and None when there
/// is no default or the audio service cannot be reached.
///
/// WebRTC's device module cannot be told "the default" by the plugin, only a
/// device by its place in the list, so choosing "System default" has to be
/// turned into a concrete endpoint first.
Future<String?> defaultOutputEndpoint() =>
    RustLib.instance.api.crateApiAudioEndpointsDefaultOutputEndpoint();

/// The id of the capture endpoint Windows records from by default. See
/// [`default_output_endpoint`].
Future<String?> defaultInputEndpoint() =>
    RustLib.instance.api.crateApiAudioEndpointsDefaultInputEndpoint();

/// One endpoint, and the format Windows hands a shared-mode client for it.
class AudioEndpoint {
  /// The endpoint id, in the same form WebRTC reports as a device's guid, so
  /// the two lists can be matched up.
  final String deviceId;
  final String name;
  final int channels;
  final int sampleRate;

  /// Whether Windows accepts any of the formats WebRTC's device module asks
  /// for. Asked of Windows rather than inferred from the mix format: inside
  /// Rift's own process a 2 channel endpoint has been seen reporting an 8
  /// channel mix, which the module opened without trouble.
  final bool opens;

  const AudioEndpoint({
    required this.deviceId,
    required this.name,
    required this.channels,
    required this.sampleRate,
    required this.opens,
  });

  @override
  int get hashCode =>
      deviceId.hashCode ^
      name.hashCode ^
      channels.hashCode ^
      sampleRate.hashCode ^
      opens.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioEndpoint &&
          runtimeType == other.runtimeType &&
          deviceId == other.deviceId &&
          name == other.name &&
          channels == other.channels &&
          sampleRate == other.sampleRate &&
          opens == other.opens;
}
