// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Encrypts `data` with AES-256-GCM under `key` (32 bytes) and `nonce`
/// (12 bytes). Returns the ciphertext with its tag appended.
Future<Uint8List> sealBlob({
  required List<int> key,
  required List<int> nonce,
  required List<int> data,
}) => RustLib.instance.api.crateApiBlobCipherSealBlob(
  key: key,
  nonce: nonce,
  data: data,
);

/// Decrypts what [seal_blob] made. Fails on a wrong key and on any change to
/// the bytes.
Future<Uint8List> openBlob({
  required List<int> key,
  required List<int> nonce,
  required List<int> sealed,
}) => RustLib.instance.api.crateApiBlobCipherOpenBlob(
  key: key,
  nonce: nonce,
  sealed: sealed,
);

/// SHA-256 of `data`: what an attachment sent unencrypted is checked against.
Future<Uint8List> digestBlob({required List<int> data}) =>
    RustLib.instance.api.crateApiBlobCipherDigestBlob(data: data);

/// Encrypts chunk `position` of a file sealed a chunk at a time, under `key`
/// and the 7-byte nonce `prefix`; `last` marks the final chunk. Returns the
/// chunk with its tag appended.
Future<Uint8List> sealBlobChunk({
  required List<int> key,
  required List<int> prefix,
  required int position,
  required bool last,
  required List<int> data,
}) => RustLib.instance.api.crateApiBlobCipherSealBlobChunk(
  key: key,
  prefix: prefix,
  position: position,
  last: last,
  data: data,
);

/// Decrypts what [seal_blob_chunk] made, at the same `position` and `last`.
Future<Uint8List> openBlobChunk({
  required List<int> key,
  required List<int> prefix,
  required int position,
  required bool last,
  required List<int> sealed,
}) => RustLib.instance.api.crateApiBlobCipherOpenBlobChunk(
  key: key,
  prefix: prefix,
  position: position,
  last: last,
  sealed: sealed,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BlobHasher>>
abstract class BlobHasher implements RustOpaqueInterface {
  /// The hash of everything given. Once only.
  Future<Uint8List> finish();

  factory BlobHasher() =>
      RustLib.instance.api.crateApiBlobCipherBlobHasherNew();

  Future<void> update({required List<int> data});
}
