// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Plays `mp3` on `device_id` — the id WebRTC lists the output under (the
/// endpoint id on Windows, the sink's description on Linux), or `None` for
/// the default — at `volume` (0 to 1), once or over and over. Answers once the
/// device has opened, or with why it would not, so the caller can fall back to
/// the default device.
///
/// Off Windows and Linux it always fails, and the caller keeps its own player.
Future<CueStarted> playCue({
  String? deviceId,
  required List<int> mp3,
  required double volume,
  required bool looping,
}) => RustLib.instance.api.crateApiCuePlayCue(
  deviceId: deviceId,
  mp3: mp3,
  volume: volume,
  looping: looping,
);

/// Turns a playing cue up or down. Nothing if it has ended.
Future<void> setCueVolume({required int id, required double volume}) =>
    RustLib.instance.api.crateApiCueSetCueVolume(id: id, volume: volume);

/// Stops a playing cue. Nothing if it has ended.
Future<void> stopCue({required int id}) =>
    RustLib.instance.api.crateApiCueStopCue(id: id);

/// A cue that is playing: what to stop or turn, and how long one pass lasts,
/// since the player does not say when it has finished.
class CueStarted {
  final int id;
  final int durationMs;

  const CueStarted({required this.id, required this.durationMs});

  @override
  int get hashCode => id.hashCode ^ durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CueStarted &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          durationMs == other.durationMs;
}
