// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Sends a [DuckingEvent] each time Windows ducks or unducks, for the life
/// of the process. Windows only; elsewhere it fails, and nothing is sent.
Stream<DuckingEvent> duckingEvents() =>
    RustLib.instance.api.crateApiDuckingDuckingEvents();

/// What Windows does to other sounds during a call: 0 mutes them, 1 lowers
/// them by 80% (also when the user never chose), 2 by 50%, 3 does nothing.
/// Read each time, since the user changes it in Windows' own Sound window.
/// Null off Windows.
int? duckingPreference() =>
    RustLib.instance.api.crateApiDuckingDuckingPreference();

/// Windows lowered other apps (`ducked`) or let them back up.
class DuckingEvent {
  final bool ducked;

  /// Whether this process's call caused it. Another app's call ducks too,
  /// and is not Rift's to explain.
  final bool byRift;

  /// The file name of the program whose call it is.
  final String app;

  const DuckingEvent({
    required this.ducked,
    required this.byRift,
    required this.app,
  });

  @override
  int get hashCode => ducked.hashCode ^ byRift.hashCode ^ app.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DuckingEvent &&
          runtimeType == other.runtimeType &&
          ducked == other.ducked &&
          byRift == other.byRift &&
          app == other.app;
}
