// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Starts writing this session's log in `dir`, with what was logged before,
/// and keeps only the newest few sessions there. Returns the file's path.
/// Calling it again returns the same path.
Future<String> startLogFile({required String dir}) =>
    RustLib.instance.api.crateApiLogsStartLogFile(dir: dir);

/// Writes one of Dart's lines to the log, from `source` (`dart`, `flutter`).
void writeLogLine({required String source, required String line}) =>
    RustLib.instance.api.crateApiLogsWriteLogLine(source: source, line: line);
