// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Reads `device_id` — an endpoint id as [`super::audio_endpoints`] reports
/// them, or `None` for Windows' default — and sends 16-bit mono samples at
/// 16 kHz to `sink` until [`stop_mic_test`], or until Dart stops listening.
///
/// A microphone that cannot be opened ends the stream with an error. Off
/// Windows the stream ends with an error straight away, and the caller keeps
/// to WebRTC's own capture.
Stream<Int16List> micTestSamples({String? deviceId}) =>
    RustLib.instance.api.crateApiMicTestMicTestSamples(deviceId: deviceId);

/// Stops the running test, if any, and releases the microphone.
Future<void> stopMicTest() => RustLib.instance.api.crateApiMicTestStopMicTest();
