// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Loads DeepFilterNet's model, if it is not loaded already, and says where
/// to call it. On a blocking thread, since loading takes a quarter of a
/// second. Off Windows and Linux there is no model, and this says so.
Future<DeepFilterEntry> loadDeepFilter() =>
    RustLib.instance.api.crateApiNoiseFilterLoadDeepFilter();

/// Where the runner's filter calls the model: the addresses of the frame
/// function and the reset function, for Dart to pass on.
class DeepFilterEntry {
  final BigInt process;
  final BigInt reset;

  const DeepFilterEntry({required this.process, required this.reset});

  @override
  int get hashCode => process.hashCode ^ reset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeepFilterEntry &&
          runtimeType == other.runtimeType &&
          process == other.process &&
          reset == other.reset;
}
