// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'screenshare/types.dart';

// These functions are ignored because they are not marked as `pub`: `emit_screenshare_event`

/// Subscribe to screenshare lifecycle events (e.g. the shared window closing).
/// Flutter listens to the returned stream for the app's lifetime.
Stream<ScreenshareEvent> screenshareEventStream() =>
    RustLib.instance.api.crateApiScreenshareScreenshareEventStream();

/// Connect a second participant to the call's room and publish the chosen
/// screen or window (and, if asked, its audio) as screen-share tracks.
///
/// Only one share runs at a time; a second call while one is up is an error
/// rather than a replacement. Off the desktop it fails outright: the caller is
/// about to show a "sharing" state for a stream that would never arrive.
Future<String> startScreenshare({required ScreenShareConfig config}) =>
    RustLib.instance.api.crateApiScreenshareStartScreenshare(config: config);

/// Stop the share and leave the room. Succeeds when nothing was running: a
/// teardown that errors would make every disconnect look like a failure.
Future<String> stopScreenshare() =>
    RustLib.instance.api.crateApiScreenshareStopScreenshare();

/// Screens, or windows, in the order their indexes refer to.
Future<List<CaptureSource>> listCaptureSources({
  required bool captureFullScreen,
}) => RustLib.instance.api.crateApiScreenshareListCaptureSources(
  captureFullScreen: captureFullScreen,
);

/// A small JPEG preview of one source, at most 320 px wide. Windows only so
/// far; elsewhere `None`, which the picker renders as a plain tile.
Future<Uint8List?> getCaptureSourceThumbnail({
  required bool captureFullScreen,
  required int sourceIndex,
}) => RustLib.instance.api.crateApiScreenshareGetCaptureSourceThumbnail(
  captureFullScreen: captureFullScreen,
  sourceIndex: sourceIndex,
);

/// Applications currently playing audio, for Linux window-capture audio.
/// Empty elsewhere: Windows chooses by the window's process id instead.
Future<List<AudioSource>> listAudioSources() =>
    RustLib.instance.api.crateApiScreenshareListAudioSources();
