// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check`, `emit_event`

/// Subscribe to sound-share lifecycle events. Flutter listens to the returned
/// stream for the app's lifetime.
Stream<SoundShareEvent> soundShareEventStream() =>
    RustLib.instance.api.crateApiSoundshareSoundShareEventStream();

/// Connect a second participant to the call's room and publish one
/// application's sound.
///
/// Only one sound share runs at a time; a second call while one is up is an
/// error rather than a replacement. A screen share may run alongside it —
/// they are separate connections with identities of their own.
Future<String> startSoundShare({required SoundShareConfig config}) =>
    RustLib.instance.api.crateApiSoundshareStartSoundShare(config: config);

/// Stop the share and leave the room. Succeeds when nothing was running: a
/// teardown that errors would make every disconnect look like a failure.
Future<String> stopSoundShare() =>
    RustLib.instance.api.crateApiSoundshareStopSoundShare();

/// What to share, and the call to share it into.
class SoundShareConfig {
  final String livekitUrl;
  final String livekitToken;

  /// Linux: the PulseAudio sink-input to capture, and the sink it plays to.
  final int? selectedAudioSourceIndex;
  final int? selectedAudioSourceSink;

  /// Windows: the process whose audio to capture; none means the whole mix.
  final int? selectedAudioSourcePid;

  /// The channel key this call is encrypted with, and the LiveKit key-ring
  /// slot it occupies (ARCHITECTURE.md §5) — the same pair a screen share
  /// carries, and for the same reason: a track published in the clear is
  /// one the server can listen to.
  final Uint8List e2EeKey;
  final int e2EeKeyIndex;

  const SoundShareConfig({
    required this.livekitUrl,
    required this.livekitToken,
    this.selectedAudioSourceIndex,
    this.selectedAudioSourceSink,
    this.selectedAudioSourcePid,
    required this.e2EeKey,
    required this.e2EeKeyIndex,
  });

  @override
  int get hashCode =>
      livekitUrl.hashCode ^
      livekitToken.hashCode ^
      selectedAudioSourceIndex.hashCode ^
      selectedAudioSourceSink.hashCode ^
      selectedAudioSourcePid.hashCode ^
      e2EeKey.hashCode ^
      e2EeKeyIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SoundShareConfig &&
          runtimeType == other.runtimeType &&
          livekitUrl == other.livekitUrl &&
          livekitToken == other.livekitToken &&
          selectedAudioSourceIndex == other.selectedAudioSourceIndex &&
          selectedAudioSourceSink == other.selectedAudioSourceSink &&
          selectedAudioSourcePid == other.selectedAudioSourcePid &&
          e2EeKey == other.e2EeKey &&
          e2EeKeyIndex == other.e2EeKeyIndex;
}

/// Lifecycle events pushed from Rust up to Flutter.
enum SoundShareEvent {
  /// The application stopped playing, or quit. There is nothing left to
  /// share, so Flutter tears the session down and updates its UI.
  sourceEnded,
}
