// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Shows the toast in `xml` for the app `app_id` (the AUMID the plugin was
/// initialised with), tagged `tag` in `group`. A toast already there with the
/// same tag and group is replaced. Windows only; elsewhere it fails.
Future<void> showWindowsToast({
  required String appId,
  required String tag,
  required String group,
  required String xml,
}) => RustLib.instance.api.crateApiToastShowWindowsToast(
  appId: appId,
  tag: tag,
  group: group,
  xml: xml,
);

/// Removes the toast [show_windows_toast] posted as `tag` in `group` for
/// `app_id`, from the screen and the notification centre. Nothing if it is
/// already gone. Windows only; elsewhere it does nothing.
Future<void> removeWindowsToast({
  required String appId,
  required String tag,
  required String group,
}) => RustLib.instance.api.crateApiToastRemoveWindowsToast(
  appId: appId,
  tag: tag,
  group: group,
);
