// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';

/// Run once at start, as early as possible. May apply an update downloaded
/// before and restart into it, in which case it does not return. Returns the
/// installed version, or `None` when this copy cannot update itself — it was
/// not installed by Rift's installer or AppImage.
Future<String?> updaterStartup() =>
    RustLib.instance.api.crateApiUpdaterUpdaterStartup();

/// Looks for a newer release; pre-releases count when `include_prereleases`.
Future<AvailableUpdate?> updaterCheck({required bool includePrereleases}) =>
    RustLib.instance.api.crateApiUpdaterUpdaterCheck(
      includePrereleases: includePrereleases,
    );

/// Downloads what [updater_check] last found. The stream carries progress
/// from 0 to 100 and ends once the update is ready, or with an error.
Stream<int> updaterDownload() =>
    RustLib.instance.api.crateApiUpdaterUpdaterDownload();

/// The version already downloaded and waiting for a restart, if any.
Future<String?> updaterPendingVersion() =>
    RustLib.instance.api.crateApiUpdaterUpdaterPendingVersion();

/// Sets the downloaded update to be put in place once this process exits;
/// Rift then starts again by itself. Quit straight after this succeeds.
Future<void> updaterApplyOnExit() =>
    RustLib.instance.api.crateApiUpdaterUpdaterApplyOnExit();

/// A release newer than the one installed.
class AvailableUpdate {
  final String version;

  /// The release notes, as written in the tag's message.
  final String notesMarkdown;

  /// What the download weighs: the changes since this version when the
  /// release carries them, otherwise the whole package.
  final int downloadBytes;

  const AvailableUpdate({
    required this.version,
    required this.notesMarkdown,
    required this.downloadBytes,
  });

  @override
  int get hashCode =>
      version.hashCode ^ notesMarkdown.hashCode ^ downloadBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AvailableUpdate &&
          runtimeType == other.runtimeType &&
          version == other.version &&
          notesMarkdown == other.notesMarkdown &&
          downloadBytes == other.downloadBytes;
}
